addon-name: "BetterBags - Mists Remix"
addon-description: "BetterBags plugin for Mists of Pandaria Remix items"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/betterbags-mistsremix"
  wago: "https://addons.wago.io/addons/qGYMkMGg"
  discord: "https://discord.gg/Qc9TRBv"
